import type { Metadata } from "next";
import "@/app/ui/globals.css";
import ThemeSwitch from "./ui/theme-switcher";
import NavBar from "./ui/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='h-screen v-screen bg-base-100 text-base-content'>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
